# Yazi theme — Catppuccin Mocha

[manager]
cwd = { fg = "#94e2d5" }

hovered = { fg = "#1e1e2e", bg = "#89b4fa" }
preview_hovered = { underline = true }

find_keyword = { fg = "#f9e2af", italic = true }
find_position = { fg = "#fab387", bg = "reset", italic = true }

marker_selected = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_copied = { fg = "#f9e2af", bg = "#f9e2af" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }

tab_active = { fg = "#1e1e2e", bg = "#cdd6f4" }
tab_inactive = { fg = "#a6adc8", bg = "#313244" }

border_style = { fg = "#6c7086" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#313244", bg = "#313244" }

mode_normal = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#f9e2af", bold = true }
mode_unset = { fg = "#1e1e2e", bg = "#f5c2e7", bold = true }

progress_label = { fg = "#cdd6f4", bold = true }
progress_normal = { fg = "#45475a", bg = "#313244" }
progress_error = { fg = "#f38ba8", bg = "#313244" }

[input]
border = { fg = "#89b4fa" }
title = {}
value = {}
selected = { reversed = true }

[select]
border = { fg = "#89b4fa" }
active = { fg = "#f5c2e7" }
inactive = {}

[tasks]
border = { fg = "#89b4fa" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#313244" }
cand = { fg = "#89b4fa" }
rest = { fg = "#6c7086" }
desc = { fg = "#fab387" }
separator = "  "
separator_style = { fg = "#45475a" }

[help]
on = { fg = "#f5c2e7" }
exec = { fg = "#94e2d5" }
desc = { fg = "#6c7086" }
hovered = { bg = "#45475a", bold = true }
footer = { fg = "#313244", bg = "#cdd6f4" }
