# Starship prompt — Catppuccin Mocha

format = """
[░▒▓](#a6adc8)\
[  ](bg:#a6adc8 fg:#1e1e2e)\
$os\
$username\
[](fg:#a6adc8 bg:#6c7086)\
$directory\
[](fg:#6c7086 bg:#89b4fa)\
$git_branch\
$git_status\
[](fg:#89b4fa bg:#f9e2af)\
$c\
$rust\
$golang\
$java\
$python\
$nodejs\
$lua\
[](fg:#f9e2af bg:#a6e3a1)\
$docker_context\
$conda\
[](fg:#a6e3a1 bg:#94e2d5)\
$nix_shell\
[](fg:#94e2d5 bg:#fab387)\
$time\
[ ](fg:#fab387)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[os]
disabled = false
style = "bg:#a6adc8 fg:#1e1e2e"

[os.symbols]
Linux = " "
Macos = " "
Windows = " "

[username]
show_always = true
style_user = "bg:#a6adc8 fg:#1e1e2e"
style_root = "bg:#a6adc8 fg:#1e1e2e"
format = '[ $user ]($style)'

[directory]
style = "fg:#cdd6f4 bg:#6c7086"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#1e1e2e bg:#89b4fa"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1e1e2e bg:#89b4fa"
format = '[$all_status$ahead_behind ]($style)'

[python]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "fg:#1e1e2e bg:#f9e2af"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#1e1e2e bg:#a6e3a1"
format = '[ $symbol $context ]($style)'

[conda]
style = "fg:#1e1e2e bg:#a6e3a1"
format = '[ $symbol $environment ]($style)'

[nix_shell]
symbol = ""
style = "fg:#1e1e2e bg:#94e2d5"
format = '[ $symbol $name ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#1e1e2e bg:#fab387"
format = '[  $time ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
